<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Ry7NxR\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Ry7NxR/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container4Ry7NxR.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container4Ry7NxR\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container4Ry7NxR\appAppKernelProdContainer([
    'container.build_hash' => '4Ry7NxR',
    'container.build_id' => '7f62b397',
    'container.build_time' => 1758335439,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Ry7NxR');
