<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3E9EWkVj8/XtTXmr9Meh'."\n".'HRb93QSqKikIeawpdewrkissW8nktt+okCL216/T8hQBCAphtM78Za0S8ByWl14l'."\n".'O4sJ5Va6hVT3+E3CuCs2lVkFT7Jq5cGdEwj0JrJhK3rdxE9aKrCgZo/kKfIu+d45'."\n".'AYbJd7XPNP8mdESXPZ4PDzEe6+yeKLkohGMeP1HoEkZAPKEldVakkp/6ivbhUF4B'."\n".'uKNBivvE059mu/dEbwgVhjbZEDNIg8L/377A3iB734ER2iAK++4sVJKa8ViooNcv'."\n".'Mfeebbs0HLPpnMV8fgoTXpqEPnKPx5pHY0Ayn750M8oUuiNyzWyebhLaThqHEPpH'."\n".'pQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
