<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfl6gUa\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfl6gUa/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfl6gUa.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfl6gUa\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerDfl6gUa\appAppKernelDevDebugContainer([
    'container.build_hash' => 'Dfl6gUa',
    'container.build_id' => '1c0d7a45',
    'container.build_time' => 1758335188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfl6gUa');
